<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://t-srvbacapplsar.tsoftglobal.com/topaz/gdeopenapi/services/GdeWsOpenAPI" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://t-srvbacapplsar.tsoftglobal.com/topaz/gdeopenapi/services/GdeWsOpenAPI" xmlns:intf="http://t-srvbacapplsar.tsoftglobal.com/topaz/gdeopenapi/services/GdeWsOpenAPI" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message profileName="getDataWebServiceResponse">

      <wsdl:part profileName="retval" type="soapenc:string"/>

      <wsdl:part profileName="errorCode" type="xsd:int"/>

      <wsdl:part profileName="origRowCount" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message profileName="getDataWebServiceRequest">

      <wsdl:part profileName="user" type="soapenc:string"/>

      <wsdl:part profileName="password" type="soapenc:string"/>

      <wsdl:part profileName="query" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType profileName="GetDataLocal">

      <wsdl:operation profileName="getDataWebService" parameterOrder="user password query errorCode origRowCount">

         <wsdl:input message="impl:getDataWebServiceRequest" profileName="getDataWebServiceRequest"/>

         <wsdl:output message="impl:getDataWebServiceResponse" profileName="getDataWebServiceResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding profileName="GdeWsOpenAPISoapBinding" type="impl:GetDataLocal">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation profileName="getDataWebService">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input profileName="getDataWebServiceRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://t-srvbacapplsar.tsoftglobal.com/topaz/gdeopenapi/services/GdeWsOpenAPI" use="encoded"/>

         </wsdl:input>

         <wsdl:output profileName="getDataWebServiceResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://t-srvbacapplsar.tsoftglobal.com/topaz/gdeopenapi/services/GdeWsOpenAPI" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service profileName="GetDataLocalService">

      <wsdl:port binding="impl:GdeWsOpenAPISoapBinding" profileName="GdeWsOpenAPI">

         <wsdlsoap:address location="http://t-srvbacapplsar.tsoftglobal.com/topaz/gdeopenapi/services/GdeWsOpenAPI"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
